# Generated by Django 3.2.9 on 2021-11-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thimbnail',
            new_name='thumbnail',
        ),
    ]
